### ISSUE TITLE
Peer dependency version

### ISSUE THREAD

**Issue by mbiegert** [pradel/esbuild-node-externals#26]
Hello there, would you mind improving the peer dependency specification of the esbuild-node-externals package? It currently specifies
`esbuild: ^0.13.0` which leads to yarn complaining when upgrading esbuild to v0.14. The reason is because the `^` only allows newer versions that do not increment the first non-zero portion of the version. In your readme you write that esbuild from version `0.8` is supported, so I suggest something like `esbuild: >0.8`.

Or probably better if you want to check for breaking changes with each release that bumps the minor version counter you could specify a range: `esbuild: 0.8 - 0.13`.

If you want to play around with the version specifier, there's this site: https://semver.npmjs.com/

**Comment by pradel** [comment]
Good point, actually with the latest feature it should probably be 12+, happy to accept a pr to fix it :)

**Comment by mbiegert** [comment]
Cool, coming right up

**Comment by pradel** [comment]
Amazing, thanks!
