### ISSUE TITLE
Bug: Using `esbuild-node-externals` breaks esbuild tree-shaking

### ISSUE THREAD

**Issue by dustinsgoodman** [pradel/esbuild-node-externals#30]
Hey there! I was attempting to debug a tree-shaking issue I was seeing and identified that when I include this package, esbuild's out-of-the-box tree-shaking fails to execute. I have a repro that you can view here: https://github.com/dustinsgoodman/serverless-microservices-graphql-template/pull/85

What I'm finding is if I include this plugin, I have my node_modules bundled up separately like I want, but then my main bundle is still including all imported functions regardless of use in the app. There are screenshots in the linked PR highlighting the lack of tree-shaking if you look for at the "sqs" imports.

Let me know what additional information I can provide.

**Comment by dmngu9** [comment]
i still dont get the issue. Can you provide more details please?

**Comment by dustinsgoodman** [comment]
Hey @dmngu9 - I think the crux of the issue is when this plugin is utilized to reduce `node_modules`, it creates a new issue where other source code is not removed whereas when the plugin is not included, those same source paths are removed from the build. If you look at these screenshots, if you look for the "lib" block specifically, you'll notice the aws/src path exists with the sqs sources when this library is utilized, but when it is not used, the sqs sources are not included. Ideally, when I use this library, the `node_modules` are excluded AND the unused sources are excluded. Right now, it's one or the other. Happy to hop on a call to help walk you through this if it's still unclear.

## With `esbuild-node-externals` enabled:
![image](https://user-images.githubusercontent.com/1815379/162839710-23c83b6a-5a2b-4c5a-9188-9506619b13c5.png)

## With `esbuild-node-externals` disabled:
![image](https://user-images.githubusercontent.com/1815379/162839739-58a3096b-8d3d-47d2-b6cf-09c4e236c6cc.png)
Filtered to exclude `node_modules` from view for clarity
![image (1)](https://user-images.githubusercontent.com/1815379/162839734-9d4d6166-32c6-4efb-8d03-d14778343a91.png)

**Comment by chrisands** [comment]
Tree-shaking isn't applied to externals.

**Comment by slavafomin** [comment]
Are you using `format: 'esm'` when building you library bundle? Also, make sure that your `package.json` has `sideEffects: false` in it. It is also a good idea to look into the generated source code to analyze the issue.

**Comment by dustinsgoodman** [comment]
@slavafomin you're the best! It was indeed the missing `sideEffects: false` in the package.json that was causing this issue. I do have 2 minor sideEffects but declaring those fixed the problem!

Full PR for context: https://github.com/dustinsgoodman/serverless-microservices-graphql-template/pull/442
<img width="1728" alt="Screenshot 2022-12-21 at 1 31 52 PM" src="https://user-images.githubusercontent.com/1815379/208987997-e199bc12-6673-4896-9400-1568527cbd32.png">
