### ISSUE TITLE
Add support for esbuild 0.17

### ISSUE THREAD

**Issue by xylix** [pradel/esbuild-node-externals#37]
The package has a peerdependency on esbuild 0.12-0.16. https://github.com/pradel/esbuild-node-externals/blob/main/esbuild-node-externals/package.json

I do not know if code changes are needed to support esbuild 0.17 but checking for those and then bumping the peer dependency is needed to enable users to install esbuild 0.17 along with this package.

**Comment by asdfjkalsdfla** [comment]
Setting packages: 'external' in the esbuild configuration may be an alternative. More details at https://esbuild.github.io/api/#packages.

**Comment by siefkenj** [comment]
It looks like setting `platform: 'node'` in esbuild now externalizes all built-in packages automatically. Possible workaround until this package is updated.

**Comment by simonmonecke1708** [comment]
@pradel Is there an issue related to esbuild 17 or is the problem just that the esbuild version is pinned to <= 16 in the package.json?
I'm not an esbuild expert, but maybe we can find someone if you describe why the update is failing right now

**Comment by pradel** [comment]
Don't know if esbuild 17 is working fine without changes.
If one can open a pr and add it to the peerdependency list and update the example dependency we can see quickly if it does work!

**Comment by pradel** [comment]
Fixed in 1.7.0
