### ISSUE TITLE
Support for esbuild v0.19

### ISSUE THREAD

**Issue by bradleygore** [pradel/esbuild-node-externals#45]
Currently, this package requires esbuild within this version range:
```
"peerDependencies": {
    "esbuild": "0.12 - 0.18"
  },
```

Alternatively, if there is some way to do within esbuild core what this packages is doing for versions after 0.18, could we document it within the readme? I did a quick look at the changelog in esbuild but am unclear on whether its enhancements make this package unneeded.

Thank you 😄

**Comment by pradel** [comment]
Feel free to open a pr for esbuild 0.19, here is an example of adding esbuild 0.18 https://github.com/pradel/esbuild-node-externals/pull/43

**Comment by bradleygore** [comment]
k, PR submitted: https://github.com/pradel/esbuild-node-externals/pull/46
