### ISSUE TITLE
Not marking packages which contains slash on its name as external

### ISSUE THREAD

**Issue by hilyafadhilah** [pradel/esbuild-node-externals#7]
First of all, thank you for this awesome plugin!

However, I run into an issue. Some npm dependencies aren't marked as external. When I check the `onResolve` code, turns out that it only checks the first part of `args.path`, split by the forward slash character. This made the plugin misses some package such as `@typegoose/typegoose`, since it will compare it to `@typegoose` and will return mismatch!

On the meantime, I have forked your repo and provided [my solution](https://github.com/hilyafadhilah/esbuild-node-externals/commit/748aad94d4f2e4bfcafe73d01b1e41a4a9d8ff1f) on this issue. You might want to implement it, or maybe you have your own fix.

**Comment by pradel** [comment]
Thanks for the report @hilyafadhilah, I totally forgot to handle scope packages. It is now fixed in the latest version :)
